### ISSUE TITLE
KOPA Windows koneelle on tarve ladata WINTAK asennuspaketti

### ISSUE THREAD

**Issue by M1kk0H** [pvarki/python-tak-rmapi#1]
Komentopaikalla KOPA on tarve ladata WINTAK sovelluksen asennuspaketti ja asentaa se julkisella Windows koneelle.

WINTAK asennuspaketti ei ole saatavilla ilman rekisteröintiä. WINTAK asennuspaketti tulee tarjoilla Jakelupalvelun kautta.

Latauslinkki  pitää saada Admin näkymään.

**Comment by rambo** [comment]
https://arkipublic.blob.core.windows.net/ohjelmistot/WinTAK-CIV-4_10.zip ja https://arkipublic.blob.core.windows.net/ohjelmistot/WinTAK-CIV-latest.zip sama sisältö mutta jos tulevaisuudessa tulee 4.11 tai lisätään se VNS plugin niin latest on aina "latest".
