### ISSUE TITLE
TAK admin sertifikaatti Admin-näkymään

### ISSUE THREAD

**Issue by M1kk0H** [pvarki/python-tak-rmapi#2]
Eeli haluaa päästä TAK:n web-gui admin-näkymään. Eeli lataa pääsyyn tarvittavan sertifikaatin Admin-näkymästä TAK admin osion alta (järjestelmäkohtainen, dynaamien tieto, joka syntyy deploimentin yhteydessä) tieto-osio. Ladattuaan sertifikaatin Eeli asentaa sen päätelaitteeseensa ja menee TAK admin osiosta näkemäänsä osoitteeseen selaimella (linkki  uuteen ikkunaan TAK admin näkymässä?).

Syyt TAK:n web-gui admin-näkymään pääsyyn:
- Missioineitten hallinta (lisääminen ja poistaminen), Missionit  mahdollistavat mm:ssa havaintojen automaattisen synkroinoinnin eri päätelaitteiden välillä (Datasync toiminnallisuus/Blugin)
- Käyttäjien poisto TAK:sta.( Tällä hetkellä käyttäjän poistaminen IDB:stä ei poista käyttäjää TAK:sta.)

Teknistä: 
@nixjra  toimittaa teknisen informaation

**Comment by rambo** [comment]
Käyttäjät joilla on RASENMAEHERissa admin-oikeudet saavat admin-oikeudet tuotteisiin integraatiorajapinnan kautta.
